// Runs the resolver over a snapshot of EVERY live manifest the
// hf-to-litertlm converter had shipped as of 2026-10-05 (71 repos, 112
// variants — fixtures/README.md regenerates it), across every platform key
// core can send and every backend hint. Guards the resolver against the real
// published data: the invariants hold for all 2272 combinations, every one of
// them is pinned to the reference reader's selection
// (fixtures/reference_goldens.json), and the dataset-shape counts fail loudly
// if regenerated fixtures change the distributions the mapping decisions were
// made against.
//
// Offline by design: the fixtures are committed and the resolver's fetch seam
// is fed from them, so nothing here touches the network. The snapshot does
// not have to follow the catalog: the opt-in live leg
// (live_hugging_face_test.dart) runs the same invariants (catalog_checks.dart)
// over whatever Hugging Face serves today, and reports how that differs from
// this snapshot without failing on it.
@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_edge_ai/core/domain/platform_types.dart'
    show PreferredBackend;
import 'package:flutter_edge_ai/core/model.dart' show ModelType;
import 'package:flutter_edge_ai/core/registry/hugging_face_resolver.dart'
    show ResolvedHfModel;
import 'package:flutter_edge_ai_litertlm/src/manifest/litertlm_manifest_resolver.dart';
import 'package:flutter_test/flutter_test.dart';

import 'catalog_checks.dart';

/// Key of a row in fixtures/reference_goldens.json — same shape the
/// regeneration dump in fixtures/README.md writes.
String _goldenKey(String repo, String? platform, PreferredBackend? hint) =>
    '$repo|${platform ?? "-"}|${hint == null ? "-" : wireName(hint)}';

void main() {
  final byRepo = loadSnapshot();

  Future<ResolvedHfModel> resolve(
    String repo, {
    String? platform,
    PreferredBackend? hint,
  }) => LitertlmManifestResolver(
    fetch: (url, headers) async => jsonEncode(byRepo[repo]),
  ).resolve(repo, platform: platform, preferredBackend: hint);

  test('the snapshot has the documented shape (71 repos, 112 variants)', () {
    expect(byRepo.length, 71);
    final variants = byRepo.values
        .expand((m) => m['variants'] as List)
        .cast<Map<String, dynamic>>()
        .toList();
    expect(variants.length, 112);
    // 21 of 112 variants carry no recommended rows (it was 32 of 51 on
    // 09-02), so the default_backend fallback is no longer the common case —
    // but it is still the only path for a platform no row names.
    expect(variants.where((v) => v['recommended'] == null).length, 21);
    // Every published variant carries the integrity pair.
    for (final v in variants) {
      expect(v['sha256'], matches(RegExp(r'^[0-9a-f]{64}$')));
      expect(v['size_bytes'], greaterThan(0));
    }
  });

  test('invariants hold for every repo × platform × backend hint', () async {
    // The invariants themselves live in catalog_checks.dart, shared with the
    // live leg.
    var combinations = 0;
    for (final entry in byRepo.entries) {
      combinations += await expectResolverInvariants(entry.key, entry.value);
    }
    expect(combinations, 71 * platformKeys.length * backendHints.length);
  });

  test('every combination matches the reference reader '
      '(fixtures/reference_goldens.json)', () async {
    // Generated by running the hf-to-litertlm readers/dart reference reader
    // over the same fixtures (fixtures/README.md). Rows worth knowing when
    // reading a mismatch: Qwen3-4B-Thinking resolves to three different
    // answers — android takes the block-32 file on gpu (its flagship
    // recommendation), ios/macos the recommended block-128 file on gpu, and
    // a platform no row names falls through to smallest-file +
    // default_backend, (block-32 file, cpu). granite-4.0-h-350m on android
    // is the `_int8_gpu` file on cpu: its recommendation rows name cpu on
    // the file that also runs on gpu.
    final goldens =
        jsonDecode(
              File(
                'test/manifest/fixtures/reference_goldens.json',
              ).readAsStringSync(),
            )
            as Map<String, dynamic>;
    // The rows are independent of the resolver under test only if the
    // reference reader produced them, so the file names the reader revision
    // it came from — written by the dump from its own pubspec.lock.
    final generator = goldens.remove('_generator') as Map<String, dynamic>?;
    expect(
      generator?['ref'],
      matches(RegExp(r'^[0-9a-f]{40}$')),
      reason:
          'reference_goldens.json does not name the reader revision that '
          'produced it — regenerate it per fixtures/README.md',
    );
    expect(goldens.length, 71 * platformKeys.length * backendHints.length);

    final mismatches = <String>[];
    for (final repo in byRepo.keys) {
      for (final platform in platformKeys) {
        for (final hint in backendHints) {
          final key = _goldenKey(repo, platform, hint);
          final golden = goldens[key] as Map<String, dynamic>?;
          expect(
            golden,
            isNotNull,
            reason: 'no reference row for $key — regenerate the goldens',
          );
          final r = await resolve(repo, platform: platform, hint: hint);
          final backend = wireName(r.runtime.preferredBackend!);
          if (r.file != golden!['file'] || backend != golden['backend']) {
            mismatches.add(
              '$key: resolver=(${r.file}, $backend) '
              'reference=(${golden['file']}, ${golden['backend']})',
            );
          }
        }
      }
    }
    expect(mismatches, isEmpty, reason: mismatches.join('\n'));
  });

  test('session_defaults distribution: the floor is set exactly where the '
      'published data sets it', () async {
    const withFloor = {
      'litert-community/DeepSeek-R1-Distill-Qwen-7B',
      'litert-community/Falcon-H1-Tiny-R-0.6B',
      'litert-community/LFM2.5-1.2B-Thinking',
      'litert-community/LFM2.5-2.6B',
      'litert-community/Nanbeige4.2-3B',
      'litert-community/Qwen3-4B-Thinking-2507',
      'litert-community/Spark-X2.5-1.7B',
      'litert-community/Spark-X2.5-4B',
      'litert-community/VibeThinker-3B',
      'litert-community/granite-4.2-3b',
    };
    for (final repo in byRepo.keys) {
      final r = await resolve(repo);
      expect(
        r.runtime.minOutputTokens,
        withFloor.contains(repo) ? 2048 : isNull,
        reason: repo,
      );
    }
  });

  test('modelType over the shipped catalog: mapped only where the family is '
      'certain, null everywhere else', () async {
    const expected = <String, ModelType?>{
      // deepseek outranks the qwen in the distill's id.
      'litert-community/DeepSeek-R1-Distill-Qwen-7B': ModelType.deepSeek,
      'litert-community/Qwen3-4B-Thinking-2507': ModelType.qwen3,
      // Qwen3ForCausalLM class token — the id alone hides the family.
      'mlboydaisuke/S1-mini-LiteRT': ModelType.qwen3,
      'litert-community/FastContext-1.0-4B-SFT': ModelType.qwen3,
      'litert-community/Jan-nano': ModelType.qwen3,
      // Speech-to-text repos whose LM is Qwen3: base_model or display_name
      // names it, so the id rule maps them. Core appends ` /no_think` only to
      // a text turn, so their audio turns go out as they are (measured on
      // litert-lm 0.17.1: with the suffix next to the audio Qwen3-ASR-1.7B
      // returned an empty transcript for every clip).
      'litert-community/Fun-ASR-Nano-2512': ModelType.qwen3,
      'litert-community/Qwen3-ASR-1.7B': ModelType.qwen3,
      'mlboydaisuke/Confucius4-R2T2-LiteRT': ModelType.qwen3,
      // Qwen3.5 switches thinking by template argument only, no /no_think.
      'litert-community/Qwen3.5-0.8B': ModelType.qwen35,
      'litert-community/Qwen3.5-2B': ModelType.qwen35,
      'litert-community/Qwen3.5-4B': ModelType.qwen35,
      'mlboydaisuke/Qwen3.5-0.8B-MTP-repro-LiteRT': ModelType.qwen35,
      'litert-community/Qwen2-VL-2B': ModelType.qwen,
      'litert-community/Qwen2.5-Coder-1.5B-Instruct': ModelType.qwen,
      'litert-community/LLaVA-OneVision-0.5B': ModelType.qwen,
      // Qwen2ForCausalLM class token.
      'litert-community/VibeThinker-3B': ModelType.qwen,
      'litert-community/Phi-4-mini-reasoning': ModelType.phi,
      // Everything else — LFM2.5, granite, SmolLM/SmolVLM, Ministral,
      // Nanbeige, Nemotron, Falcon-H1, HunYuan-MT, Shieldstral, InternVL,
      // MiniCPM, Spark, sarashina, … — has no ModelType, and prose like
      // "Llama-architecture granite decoder" must not create one.
      'litert-community/Agents-A1-4B': null,
      'litert-community/Falcon-H1-0.5B-Instruct': null,
      'litert-community/Falcon-H1-1.5B-Deep-Instruct': null,
      'litert-community/Falcon-H1-1.5B-Instruct': null,
      'litert-community/Falcon-H1-3B-Instruct': null,
      'litert-community/Falcon-H1-Tiny-R-0.6B': null,
      'litert-community/Hy-MT2-1.8B': null,
      'litert-community/InternVL3-1B': null,
      'litert-community/InternVL3-2B': null,
      'litert-community/InternVL3_5-1B': null,
      'litert-community/InternVL3_5-2B': null,
      'litert-community/InternVL3_5-4B': null,
      'litert-community/LFM2.5-1.2B-Instruct': null,
      'litert-community/LFM2.5-1.2B-JP': null,
      'litert-community/LFM2.5-1.2B-Thinking': null,
      'litert-community/LFM2.5-2.6B': null,
      'litert-community/LFM2.5-230M': null,
      'litert-community/LFM2.5-VL-1.6B': null,
      'litert-community/LFM2.5-VL-3B': null,
      'litert-community/LFM2.5-VL-450M': null,
      'litert-community/Mage-VL': null,
      'litert-community/MiniCPM5-2B': null,
      'litert-community/Ministral-3-3B-Instruct-2512': null,
      'litert-community/Ministral-3-3B-Reasoning-2512': null,
      'litert-community/Nanbeige4.1-3B': null,
      'litert-community/Nanbeige4.2-3B': null,
      'litert-community/Nemotron-3-Nano-4B': null,
      'litert-community/North-Micro-Vision-Instruct': null,
      'litert-community/OLMo-2-1B-Instruct': null,
      'litert-community/Ovis2.5-2B': null,
      'litert-community/PaddleOCR-VL-1.6': null,
      'litert-community/Shieldstral-1.0-3B': null,
      'litert-community/SmolLM3-3B': null,
      'litert-community/SmolVLM2-2.2B': null,
      'litert-community/SmolVLM2-500M': null,
      'litert-community/Spark-X2.5-1.7B': null,
      'litert-community/Spark-X2.5-4B': null,
      'litert-community/Zamba2-1.2B-instruct': null,
      'litert-community/granite-4.0-h-1b': null,
      'litert-community/granite-4.0-h-350m': null,
      'litert-community/granite-4.1-3b': null,
      'litert-community/granite-4.2-3b': null,
      'litert-community/granite-docling-258M': null,
      'litert-community/sarashina2.2-0.5b-instruct-v0.1': null,
      'litert-community/sarashina2.2-1b-instruct-v0.1': null,
      'mlboydaisuke/MiniCPM5-2B-LiteRT': null,
      'mlboydaisuke/Mordant-3B-Think-LiteRT': null,
      'mlboydaisuke/Tashkeel-350M-v2-LiteRT': null,
      // Speech-to-text on a Qwen2.5-shaped LM that only the architecture
      // prose names.
      'litert-community/VibeVoice-ASR-BitNet': null,
      'litert-community/VibeVoice-ASR-Streaming-1.5B': null,
      // Finetunes whose ids drop the family and whose architecture names it
      // only in prose ("Qwen3.5-0.8B gated-delta hybrid …", "built on
      // Qwen3-4B"): the conservative mapping returns null rather than guess —
      // the app supplies the type (`r.modelType ?? ModelType.general`).
      'litert-community/Polaris-4B-Preview': null,
      'litert-community/decider-0.8b-LiteRT': null,
      'litert-community/decider-2b-vision-LiteRT': null,
      'mlboydaisuke/OvisOCR2-LiteRT': null,
    };
    expect(expected.length, byRepo.length);
    for (final entry in expected.entries) {
      final r = await resolve(entry.key);
      expect(r.modelType, entry.value, reason: entry.key);
    }
  });

  test('thinking is declared by exactly the 25 repos that declare it, with '
      'their markers intact in the manifest', () async {
    const thinkingRepos = {
      'litert-community/Agents-A1-4B',
      'litert-community/DeepSeek-R1-Distill-Qwen-7B',
      'litert-community/Falcon-H1-Tiny-R-0.6B',
      'litert-community/Jan-nano',
      'litert-community/LFM2.5-1.2B-Instruct',
      'litert-community/LFM2.5-1.2B-JP',
      'litert-community/LFM2.5-1.2B-Thinking',
      'litert-community/LFM2.5-2.6B',
      'litert-community/LFM2.5-230M',
      'litert-community/MiniCPM5-2B',
      'litert-community/Ministral-3-3B-Reasoning-2512',
      'litert-community/Nanbeige4.1-3B',
      'litert-community/Nanbeige4.2-3B',
      'litert-community/Nemotron-3-Nano-4B',
      'litert-community/Phi-4-mini-reasoning',
      'litert-community/Polaris-4B-Preview',
      'litert-community/Qwen3-4B-Thinking-2507',
      'litert-community/SmolLM3-3B',
      'litert-community/Spark-X2.5-1.7B',
      'litert-community/Spark-X2.5-4B',
      'litert-community/VibeThinker-3B',
      'litert-community/granite-4.2-3b',
      'mlboydaisuke/MiniCPM5-2B-LiteRT',
      'mlboydaisuke/Mordant-3B-Think-LiteRT',
      'mlboydaisuke/S1-mini-LiteRT',
    };
    for (final repo in byRepo.keys) {
      final r = await resolve(repo);
      expect(r.runtime.thinkingDeclared, thinkingRepos.contains(repo), reason: repo);
    }
    // The channel markers stay exact in the data (whitespace included) even
    // though v1 consumes only the declared bool — worth pinning so a future
    // createSession(defaults:) can rely on them.
    final qwen = byRepo['litert-community/Qwen3-4B-Thinking-2507']!;
    final channel =
        (((qwen['model'] as Map)['capabilities'] as Map)['thinking']
                as Map)['channel']
            as Map;
    expect(channel['start'], '<think>\n');
    expect(channel['end'], '\n</think>');
  });
}
